EMPTY_CELL = 0
WALL = 1
PLAYER_ON_EMPTY_CELL = 2
PORTAL = 3
PLAYER_ON_PORTAL = 5
ENEMY_ANT = 6

PLAYER_CONTAINER_CELLS = [PLAYER_ON_EMPTY_CELL, PLAYER_ON_PORTAL]
PLAYER_MOVABLE_CELLS = [EMPTY_CELL, PORTAL]
ENEMY_MOVABLE_CELLS = [EMPTY_CELL, PLAYER_ON_EMPTY_CELL]
